### ISSUE TITLE
useState(..) Hook example uses ++ in a confusing way

### ISSUE THREAD

**Issue by ptcc** [getify/tng-hooks#13]
In the following code the   `++count` is used only to print 1 instead of 0, 2 instead of one, since the actual state changing occurs on updateCount.
If that's on purpose, then it should be replaced with `count + 1`

As is this example is just confusing because `++count` looks like an attempt to change state

```
function hit() {
    var [count,updateCount] = useState(0);

    updateCount(onUpdateCount);

    console.log(`Hit count: ${++count}`);
}

function onUpdateCount(oldCount) {
    return oldCount + 1;
}

hit = TNG(hit);

hit();       // Hit count: 1
hit();       // Hit count: 2
hit();       // Hit count: 3
```

**Comment by getify** [comment]
So `++count` would have been better as  `count+1`?

**Comment by ptcc** [comment]
yes :)
