### ISSUE TITLE
why `tngStack`

### ISSUE THREAD

**Issue by GuichiZhao** [getify/TNG-Hooks#24]
If I am correct, the size of `tngStack` is never larger that 1, so why not put something like `currentTng`? why use an array and push and pop every time?

**Comment by pkoch** [comment]
This is not true. Think of th case where an articulated function calling another one.

**Comment by GuichiZhao** [comment]
@pkoch I do not think calling an articulated function inside another articulated function is a valid use case, it will not trigger an error though @getify

**Comment by getify** [comment]
It is a valid use case, like in React if one component calls anothrr component. That's the purpose of the tng-stack.
