### ISSUE TITLE
Support: useEffect(..) hook

### ISSUE THREAD

**Issue by getify** [getify/tng-hooks#3]
Support a `useEffect(..)` hook similar in spirit to [React's `useEffect(..)` hook](https://reactjs.org/docs/hooks-effect.html). Potentially rename ours to `useDeferred(..)` to better reflect what it does.

The asynchronous deferral that should occur will not be as controlled as with React, since they base its execution on the React lifecycle. It could be as simple as `setTimeout(..0)` / `setImmediate(..)` / `process.nextTick(..)`, or `Promise.resolve().then(..)` (microtask), or possibly just `requestAnimationFrame(..)`. Need to figure out which async deferral strategy makes sense, or which combination of them for cross-platform.

~~It's critical that the deferred effect is given the same hook context as the parent function, so that it can use `useState(..)`, etc.~~

Similar to React's implementation, `useEffect(..)` needs to take a list of state variables to determine if the deferred effect should run that time or not. It only runs if the list is omitted, or if the list contains different state values than the last time it ran. If the list is empty, the hook only runs the first time.

For example:

```js
function foo(text) {
   var [el,setEl] = useState(null);

   useEffect(
      function onInitialRender(){
         var [el,setEl] = useState(null);
         setEl(el = document.createElement("span"));
         document.body.appendChild(el);
         el.addEventListener(.....);

         // manually trigger a re-render
         foo(text);
      },
      []  // only run this hook once at the beginning
   );

   useEffect(
      function onReRender() {
         el.innerHTML = text;
      },
      [el,text]   // only run when either text or el have changed
   );
}
```

Also, if the deferred effect itself returns a cleanup function, this function will be saved and run right before the next deferred effect runs.

One tricky thing to work out: when will the "last" cleanup function be run? Since we don't have a lifecycle, there's no event to trigger that. It could be that we just never fire it, or that we need to provide some programmatic way to trigger "finalization" of a function. Maybe all TNG-wrapped functions have an additional `.finalize()` on them?

**Comment by j3ski** [comment]
Hi,
Nice work on bringing hooks to plain js :) I'd like to share my thoughts on the `useEffect` potential implementation.

1. On the deferral method I think that there could be multiple methods, using different strategies, as React uses `useEffect` for "totally" async (so the cross-platform counterpart would be `setTimeout` I think), and `useLayoutEffect` for a "sync" effect, running after component mount/update (here I'd see a microtask?)
2. I don't quite get why it's critical for the effect hook to have the same tng context as the function calling it. I think the preferred way would be to create a custom hook, which would first call `useState` and then use the state/setState callback inside useEffect.
Look at the following example
```js
//wrapped in tng
function example() {
  useEffect(
    () => {
      const [state, setState] = useState(1);
      console.log('First effect run', state, 'times');
      setState(state + 1);
    },
    [],
  );

  useEffect(
    () => {
      const [state, setState] = useState(1);
      console.log('Second effect. Always logs 1, right?', state);
    }
  )
}

example();
example();
```
This breaks the 1 Hook call rule, as the first effect is run conditionally.
Instead of this, if the user really wants to use other hooks inside the callback, they might wrap it in tng instead, to create their own context. Then everything should be fine (maybe provide a `useTNG` hook to enable creation of functions with context "the hook way"?)
3. Cleanup. I don't think this will be able until weakRefs land in javascript-land. The good thing is that TC is working on it already (https://github.com/tc39/proposal-weakrefs) and WASM would also benefit, so it can make it to the spec. For node I've found https://github.com/TooTallNate/node-weak which could make it work even today (would probably require some periodical check if the original function was gc'd already)
4. If `finalize` would be added, what will be the behavior of the function when it is called and:
i. There is no cleanup yet (the effect hasn't run yet)
ii. The user wants to run the function again (should it be prohibited? Probably yes, as the function should be treated as gc'd).

**Comment by krizka** [comment]
About 2. Agreeing with @j3ski, you never need to call other effects from `useEffect(...)` conditionally, if you need - call it outside of `useEffect` inside context of parent wrapped function:
```js
function example() {
  const [state, setState] = useState(1);
  useEffect(
    () => {
      console.log('First effect run', state, 'times');
      setState(state + 1);
    },
    [],
  );
}
```

**Comment by getify** [comment]
I was thinking that being able to call useState/useReducer hooks (not useEffect) from inside an effect would mean your effect wouldn't have to be embedded inside the parent just for you to access any state variables (via closure). Also, since effects are async, closing over a state variable might mean the effect uses a stale value for that state, instead of pulling a fresh copy via useState. I personally think this is a weakness of React's current implementation, so this would be a deviation from them in terms of experimenting with that improvement. Thoughts?

**Comment by jedrzej-bridgemaker** [comment]
I understand your point, but sharing the parent function's context would mean having the problems I mentioned (assuming we can't get around hook rule no. 1). What I'd suggest would be to have `useEffect` memoize and wrap it's argument in tng, to give it it's own context.
This would probably require another change to React's implementation: passing the second argument as arguments to the effect handler (so in fact making the second arg mandatory).

**Comment by j3ski** [comment]
I understand your point, but sharing the parent function's context would mean having the problems I mentioned (assuming we can't get around hook rule no. 1). What I'd suggest would be to have useEffect memoize and wrap it's argument in tng, to give it it's own context.
This would probably require another change to React's implementation: passing the second argument as arguments to the effect handler (so in fact making the second arg mandatory).

**Comment by getify** [comment]
I think it's important to note, TNG is not as constrained by the "hook rules" as is React. Specifically, [quoting from the README docs for TNG](https://github.com/getify/tng-hooks#hook-call-rules):

> It is absolutely required that hooks always be called in the same order. That is, that you must never have an invocation of a function that skips over an earlier hook call but then tries to invoke one of the subsequent hook calls. THIS WILL BREAK!
>
> However, it is still technically possible to have hook calls in conditional situations (or even loops!), as long as you are very careful to never skip calls in an unsafe ordering manner.
>
> If you have three hook calls (A, B, and C) in a function, these are the valid call ordering scenarios:
>
> - A, B, C
> - A, B
> - A
> These are invalid scenarios and will break:
>
> - B, C
> - A, C
> - B
> - C

I think in the provided code example, both effects would run, in order, on the first call, so that would be two separate state units created, the first one set to value `2` and the second one set to value `1`. Then on subsequent calls, only the second effect would run, and its `useState(..)` call would be accessing the first slot, which was value `2`. So `2` would be logged from there on out, not `1`.

Now, that might indeed be a "bug", and is clearly a gotcha that you should be avoiding. But it's not broken TNG. I'm not entirely convinced that it's symptomatic of "bad design" of effects that they access state units of the parent.

Couldn't we just as easily say that one of the "rules" is, don't access state units in two different effects unless both effects always run?

**Comment by j3ski** [comment]
Agreed, that thg shouldn't be constrained as (or at least start off with the constrains of) React Hooks, but for me this is introducing a "gotcha" that can cause many headaches.
Say, I have a function
```js
function getUser(userId) {
  const usersCollection = useMongo('users');
  useLogger(() => `Getting user with id ${userId}`);

  return usersCollection.findById(userId);
}
```
As a developer, this looks completely valid, but stops working on the second call. The reason being, that useMongo and useLogger internally call `useEffect`, which in turn calls `useState`. The difference is, useMongo calls the effect once (to connect to the database), while `useLogger` calls the  effect on every run.
Neither `useLogger` nor `useMongo` don't break any rules by themselves (no branching!), but used together break, so now I need to know their implementation before I use them. I don't want to use leaky abstractions!

**Comment by getify** [comment]
I can see the concern you bring up. But allow me to just poke at this a tad... if `useMongo(..)` and `useLogger(..)` both have effects, wouldn't both of those be there own TNG wrapped functions, to isolate their respective states from each other?

I guess what I'm getting at is, it surprises me to consider custom hooks with effects at all. Maybe we shouldn't even allow that? Maybe custom hooks should only be able to access state units, but not effects... and effects then only work from directly inside a TNG wrapped function?

----

AFAICT, React doesn't have to worry about this problem, at the moment, because they don't let you access any hooks inside an effect. So that seems like an attractive simplification.

However, that means the scenario you're suggesting is not even possible in React -- so we don't have the case where someone would be expecting something (like the `useMongo(..)` / `useLogger(..)` gotcah) from React but it seeing it behave differently inTNG. Rather, this is "uncharted territory" where we're considering new behavior. We can thus decide under what conditions any new behavior can be added, and if we need certain constraints or rules to make sure the new stuff is "safe".

My proposition to consider:

1. Only `useState(..)` / `useReducer(..)` (and any other state-oriented hooks) can be accessed in custom hooks.

2. Thus, `useEffect(..)` can only be accessed from a directly TNG-wrapped function, not from a custom hook.

With those "rules", don't we avoid any of the concerns you're discussing? Or am I missing something?

**Comment by getify** [comment]
Actually, I guess React does allow effects inside of custom hooks (but not other effects). But that still surprises me. I'm not sure why that should be allowed in either React or TNG?

**Comment by j3ski** [comment]
Yes, React does allow `useEffect()` in custom hooks and it makes perfect sense for them, see: [useWindowWidth](https://gist.github.com/gaearon/cb5add26336003ed8c0004c4ba820eae#file-usewindowwidth-js) for example. The reason being that `useState()` in tng is somewhat a glorified closure, while in React-world it carries additional functionality - forces the component to re-render when `setState()` is called. Maybe tng should also provide such a functionality (say, second argument to `useState()`, being a callback to run whenever `setState()` is called)?

Your proposed solution fixes my concerns, but then it introduces even more rules to use hooks (which isn't necessarily a bad thing). The thing that would bother me more is the fact, that hooks were created to enable logic re-use, but not allowing to use effects in custom hooks feels like a major drawback (unless you wrap the custom hook in tng, which most people would probably start to do anyway).

**Comment by getify** [comment]
I think your last point is important. In TNG the point of a "custom hook" is only to share the "state" of the parent. If you want a thing that can have its own side effects, that really should be its own TNG wrapped a context. Having very indirect side effects -- effects inside of a custom hook that was called by another custom hook that was valled by another.... this seems like a horrible idea for code maintability.

Setting aside any other concerns being discussed here, it seems like a natural "best practice" to either share state or create side effects, but never both in the same function.

**Comment by gaearon** [comment]
@getify Anything in particular I can answer without diving too deep? We intentionally don't let you call Hooks outside of top level. Not just because of technical limitations but because semantics can become deeply confusing. See https://github.com/reactjs/rfcs/pull/68#issuecomment-439314884.

**Comment by getify** [comment]
@gaearon several, but I'll ask them one at a time:

1. (similar to a tweet thread we had recently) Do you have any concerns about an effect closing over a state variable but since it's async it could be closed over a value that's stale? This is as opposed to, as I'm proposing, being able to call a `useState(..)` hook from inside the effect so that the effect can access the same state slots at the parent function, and always make sure it's got the current latest version of that state.

**Comment by gaearon** [comment]
>Do you have any concerns about an effect closing over a state variable but since it's async it could be closed over a value that's stale?

It is annoying for some cases indeed. But it's actually a nice property for concurrent mode because it solves a bunch of possible race conditions. So it's more effort to get right upfront but less bugs later. Of course that specifically applies to how we use it in React.

**Comment by FredyC** [comment]
@getify I am not Dan so just my 2 cents :) In my opinion, it's a rare theoretical scenario to have such deep use of custom hooks. I have been fiddling with hooks in a real production app and haven't come up with a situation where I would need something like that.

However, if something like that is really needed, I don't see why it should be any harder to debug. Yes, effects run in async, but you are defining effects synchronously. There shouldn't be any problem to just set a breakpoint in the component and step through its hooks to see what's in the box. Alternatively, you can put a debugger inside the React `useEffect` call to see all effects that are being registered/triggered in a given period of time.

**Comment by gaearon** [comment]
>If a component called a custom hook, which called a second custom hook, which called a third custom hook, and in that third hook it created an effect... Do you have any concerns about the indirect nature of that call chain producing effects on the top-level component function and making those sorts of effects hard to see and maintain/debug if they're strewn about the code?

I don't think it's really that different from e.g. `componentDidMount` calling `subscribeToSocket` calling `setupSocket`. The call chain is explicit and you can always follow it, but the effect encapsulation is considered a feature. Note that the `use` naming convention is a big part of this — we want it to be easily visible *which* calls are potentially stateful/effectful. We don't want an effect to hide inside a "normal" function. And whenever you see a `useSomething` call, you can assume there might be state or effect there. That makes it more powerful, but that's the tradeoff. In case of React, this power gets dispersed elsewhere anyway, but in a less clear way (such as higher-order components). At least with Hooks it's easy to trace, including with a debugger step through.

>The alternative, to restrict this scattering of effects, as I'm proposing, would be that neither effects nor custom hooks could create other effects, and that effects could only be created directly inside the top-level TNG function (aka, React component function). Of course, a custom hook could still use other hooks (useState(..), etc)... just not useEffect(..).

For us, that would make the whole thing not worth it. The ability to encapsulate effects is a really big use case for React because Hooks often need to hide subscriptions or other things that tie into the lifecycle.

**Comment by getify** [comment]
OK, I appreciate the feedback, y'all. I still think I wish that effects could access state hooks, and I still think custom hooks making effects is a not-so-great idea/pattern. BUT... I'm not compelled enough in that to feel like it makes sense to diverge from React here. The benefit doesn't outweigh the cost. So... we'll stick with how React does it: effects have no hooks, and custom hooks can make effects.

**Comment by getify** [comment]
I'm now thinking that since TNG hooks are not really expected to be used in the same context as React hooks, which is that we're not expecting them to be orchestrated by a framework the way React does. There's no implicit lifecycle, etc.

That leads me to think we should simplify the design of them to **not need to be** async... but rather have them be like the `finally { .. }` clause, which is that they run immediately after the function that invoked them (conditional of course on the state value matching, if any).

What remains in terms of open questions is:

* Do we provide a `finalize()` method (similar to the idea of unmounting a component) on TNG-wrapped functions, so any last cleanup function(s) -- that is, any function(s) returned from `useEffect(..)` hooks -- are ensured to run?

   I think this is the only way to mimic this part of the React lifecycle without a framework, so I think we have to. The cleanup functions can be run right before the TNG function is run on all subsequent calls, but to make sure the last cleanup happens, we have to know that you're *done* (aka, "not going to re-render") with the TNG-wrapped function.

   Should it be called `finalize()`? Should it be called `unmount()` to more closely mimic the React roots here?

* Of course, you could "finalize" a TNG-function, running all the cleanups, **then** run it again and it would function like a completely new call to it. So it would seem like in that case, it should then reset all the internal state slots of that TNG-wrapped function, right?

**Comment by getify** [comment]
**UPDATE:** I've implemented `useEffect(..)` and have all passing tests. I'm holding off on release until a decision in #7 and according updates to docs (and error messages).

* Effects are synchronous and run in order, but they run as if in a `finally {..}`, after the TNG-wrapped function has completed. **NOTE:** I plan to document that you should never rely on the synchrony or ordering of effects, as this may change in the future.

* If an effect returns a cleanup function, it's run (again, in order of the original effects) right before the next invocation of the TNG-wrapped function.

* To ensure any "final" cleanup functions are run, TNG-wrapped functions have a `reset()` function on them now. This `reset()` not only calls all the cleanups, but also resets all the internal state of the TNG-wrapped function. At that point, the TNG-wrapped function can be re-invoked as original.

**Comment by getify** [comment]
**NOTE:** The name decided in #7 is "Articulated Functions" (to describe TNG-wrapped functions that are given a TNG hook context).

**Comment by getify** [comment]
Released this `useEffect(..)` hook in v4.0.0 just now. Thanks everyone for input!
