### ISSUE TITLE
Refactor useState (or useReducer)

### ISSUE THREAD

**Issue by pomber** [getify/tng-hooks#5]
useState could be implemented using useReducer (and vice versa). Using one to implement the other may make the code easier to read/maintain.

[React](https://github.com/facebook/react/blob/5045763064/packages/react-reconciler/src/ReactFiberHooks.js#L334) does something like this:
```js
function useState(initialVal) {
  return useReducer(
    (state, action) => (typeof action === "function" ? action(state) : action),
    initialVal
  );
}
```

**Comment by getify** [comment]
Great idea, thanks!
