### ISSUE TITLE
Further clarification for useEffect() hook

### ISSUE THREAD

**Issue by aminpaks** [getify/tng-hooks#9]
IMHO the phrase below should be rephrased as it causes confusions for some.

>While not required, it's a very good idea and best practice to always pass the same guard list to an effect (even though the values can and do change)

React docs have this api better worded, specifically mentioning the usage (only) for performance optimizations. Most people see a "best practice" as a standard way of doing something, but this is not necessarily true about this api. 

Maybe just by not including "best practice" we can avoid any confusions but I'll let you handle it.

**Comment by aminpaks** [comment]
>if you have an effect that depends on entirely different state each time it's invoked, this is a "smell" that strongly suggests your effect is overloaded in a confusing way

That's not completely true. What if there is a simple hook that doesn't depend on interval values and its purpose is to just retrieve a global value?

Here is [an example](https://github.com/rehooks/window-size).

**Comment by getify** [comment]
Just to clarify... and I believe I also make this point in the docs... the primary (not only) purpose of the conditional guards is indeed for performance.

What I was saying above is that the additional "best practice" claim I'm making is, specifically, if you're going to pass any conditional guards, you should pass the same list each time. The reason for that additional claim is not really performance, it's the other stuff.

**Comment by aminpaks** [comment]
Again I'm not here to force you into anything.

As an individual when I read both "Not required" and "Best practice" to getter I get confused (maybe only me?).

**Comment by getify** [comment]
> Again I'm not here to force you into anything.

Nothing forced here. I'm appreciating your input, and asking for more elaboration.

----

One alternative (to the confusion you're reporting) is to say nothing at all, provide no guidance, and let people figure their own practices out.

Another alternative is to make this suggestion (same list every time) instead required, and throw an exception if not followed. That way the "best practice" is required.

TBH both those sound like bad options. But perhaps I'm missing something?

I made it (the choice of what guards list to pass) optional because I like builiding tools that give people flexibility. But as an educator, I feel it's also important to make suggestions about what I think are the "best" paths to stick to. Perhaps some may find benefit out of being able to go around the best practice as I defined it, but I'm thinking the majority will be best served sticking to my suggestion.

Again, I appreciate the discussion and welcome any further feedback.

**Comment by aminpaks** [comment]
>One alternative (to the confusion you're reporting) is to say nothing at all, provide no guidance, and let people figure their own practices out.

I think that's what React docs have done. They ease the readers into the concept and the api step by step without suggesting what is better than the other, simply explain the options.

It's up to you if you wanna change the api to require the argument, but that will compromise the flexibility.

All I'm saying is labeling an optional api as "best practice" is not the best way to give suggestion. Maybe just mentioning both options and why they are presented would be enough for the readers.

**Comment by getify** [comment]
> All I'm saying is labeling an optional api as "best practice" is not the best way to give suggestion. 

I think this may be where the confusion actually lies, and perhaps suggests what I need to fix.

I am not saying that the optional API (passing of a guard list) is a "best practice". I'm saying something a bit more nuanced, and it seems that part was misleading in your reading:

1. This API (passing of a guard list) is indeed **optional**, plain and simple. It's neither bad nor good practice to use it. It's almost entirely a performance-based decision. Use it if it's appropriate, don't if not. I am not prescribing any decision either way.

2. But IF you are going to pass the guard list, an additional "best practice" suggestion I'm adding to consider is that you should always pass the same guard list (for all the reasons explained earlier in this thread).

IOW, the usage of the guard list is optional (just as in React), but if you opt for it, there's a suggested best-practice way to use it (which is my addition).

Does that clarification help?

**Comment by aminpaks** [comment]
Absolutely.

I just realized that this confusion might never occur to others. (sorry my bad!) For some reasons I read those two phrases as one sentence and got the idea wrong!

**Comment by getify** [comment]
Thanks for the great input. I will try to review/clarify the docs to make sure this confusion is less likely for others. Appreciate it!
